<?php
// Database Configuration (Generated by Installer)
define('DB_TYPE', 'mysql');
define('DB_HOST', 'localhost');
define('DB_NAME', 'qjixoiuxhk_ojgherbal');
define('DB_USER', 'qjixoiuxhk_ojgherbal');
define('DB_PASS', 'ojgherbal22@@');
define('DB_PORT', 3306);
?>