<?php
/**
 * OJG Herbal - Backend Installer
 */

// Define APP_ROOT
define('APP_ROOT', dirname(__DIR__) . '/backend');

// Helper function to sanitize input
function clean_input($data)
{
    return htmlspecialchars(stripslashes(trim($data)));
}

// Check if already installed
if (file_exists(APP_ROOT . '/config/db_config.php')) {
    $installed = true;
} else {
    $installed = false;
}

$message = '';
$messageType = '';

// Handle Form Submission
if ($_SERVER["REQUEST_METHOD"] == "POST" && !$installed) {
    $db_host = clean_input($_POST['db_host']);
    $db_name = clean_input($_POST['db_name']);
    $db_user = clean_input($_POST['db_user']);
    $db_pass = $_POST['db_pass']; // Don't trim password
    $db_port = clean_input($_POST['db_port']);

    if (empty($db_host) || empty($db_name) || empty($db_user)) {
        $message = "Please fill in all required fields.";
        $messageType = "error";
    } else {
        try {
            // Test Connection
            $dsn = "mysql:host=$db_host;port=$db_port;dbname=$db_name;charset=utf8mb4";
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];

            $pdo = new PDO($dsn, $db_user, $db_pass, $options);

            // Connection Successful - Write Config
            $configContent = "<?php\n";
            $configContent .= "// Database Configuration (Generated by Installer)\n";
            $configContent .= "define('DB_TYPE', 'mysql');\n";
            $configContent .= "define('DB_HOST', '" . addslashes($db_host) . "');\n";
            $configContent .= "define('DB_NAME', '" . addslashes($db_name) . "');\n";
            $configContent .= "define('DB_USER', '" . addslashes($db_user) . "');\n";
            $configContent .= "define('DB_PASS', '" . addslashes($db_pass) . "');\n";
            $configContent .= "define('DB_PORT', " . intval($db_port) . ");\n";
            $configContent .= "?>";

            if (file_put_contents(APP_ROOT . '/config/db_config.php', $configContent)) {

                // Run Schema
                $schemaFile = APP_ROOT . '/database/schema_mysql.sql';
                if (file_exists($schemaFile)) {
                    $sql = file_get_contents($schemaFile);

                    // Split by semicolon
                    $statements = array_filter(array_map('trim', explode(';', $sql)));

                    foreach ($statements as $stmt) {
                        if (!empty($stmt)) {
                            try {
                                $pdo->exec($stmt);
                            } catch (PDOException $e) {
                                // Continue on error (e.g. table exists)
                            }
                        }
                    }

                    // Create default admin user
                    try {
                        $password = password_hash('admin123', PASSWORD_DEFAULT);
                        $stmt = $pdo->prepare("INSERT INTO admin_users (username, email, password_hash, full_name, role, status) VALUES (?, ?, ?, ?, ?, ?)");
                        $stmt->execute(['admin', 'admin@ojgherbal.com', $password, 'System Administrator', 'admin', 'active']);
                    } catch (PDOException $e) {
                        // Ignore if admin already exists
                    }

                    $message = "Installation successful! Configuration saved and database set up. Default admin user created.";
                    $messageType = "success";
                    $installed = true;

                } else {
                    $message = "Configuration saved, but schema file not found. Please import 'backend/database/schema_mysql.sql' manually.";
                    $messageType = "error";
                }

            } else {
                $message = "Failed to write configuration file. Please check permissions for 'backend/config/'.";
                $messageType = "error";
            }

        } catch (PDOException $e) {
            $message = "Database connection failed: " . $e->getMessage();
            $messageType = "error";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OJG Herbal - Backend Installer</title>
    <link rel="stylesheet" href="install.css">
</head>

<body>
    <div class="container">
        <div class="header">
            <div class="logo">🌿 OJG Herbal</div>
            <h1>Backend Installer</h1>
        </div>

        <?php if ($message): ?>
            <div class="alert alert-<?php echo $messageType; ?>">
                <?php echo $message; ?>
            </div>
        <?php endif; ?>

        <?php if ($installed): ?>
            <div style="text-align: center;">
                <p>The system is successfully installed.</p>
                <p>You can now access the admin panel.</p>
                <a href="../backend/admin/"
                    style="display: inline-block; background-color: #059669; color: white; padding: 0.75rem 1.5rem; text-decoration: none; border-radius: 0.375rem; font-weight: 500; margin-top: 1rem;">Go
                    to Admin Panel</a>
                <p style="margin-top: 1rem; font-size: 0.875rem; color: #6b7280;">
                    Default Credentials:<br>
                    Username: <strong>admin</strong><br>
                    Password: <strong>admin123</strong>
                </p>
                <div class="alert alert-error" style="margin-top: 1.5rem; text-align: left;">
                    <strong>⚠️ Security Warning:</strong><br>
                    Please delete the entire <code>install</code> folder from your server immediately after verifying the
                    installation to prevent security risks.
                </div>
            </div>
        <?php else: ?>
            <form method="POST" action="">
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" id="db_host" name="db_host" value="localhost" required>
                </div>

                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" id="db_name" name="db_name" placeholder="ojg_herbal" required>
                </div>

                <div class="form-group">
                    <label for="db_user">Database Username</label>
                    <input type="text" id="db_user" name="db_user" placeholder="root" required>
                </div>

                <div class="form-group">
                    <label for="db_pass">Database Password</label>
                    <input type="password" id="db_pass" name="db_pass" placeholder="Leave empty if none">
                </div>

                <div class="form-group">
                    <label for="db_port">Database Port</label>
                    <input type="text" id="db_port" name="db_port" value="3306" required>
                </div>

                <button type="submit">Install & Setup Database</button>
            </form>
        <?php endif; ?>

        <div class="footer">
            &copy; <?php echo date('Y'); ?> OJG Herbal. All rights reserved.
        </div>
    </div>
</body>

</html>